name         'gsick-jetty'
version      '0.0.8'
source       'https://github.com/gsick/puppet-jetty.git'
author       'Gamaliel Sick'
license      'MIT'
summary      'Jetty installation and configuration module'
description  'Puppet module for installing and configuring Jetty'
project_page 'https://github.com/gsick/puppet-jetty'

dependency   'puppetlabs/stdlib', '>= 4.1.0'
dependency   'puppetlabs/java', '>= 1.0.1'
dependency   'pdxcat/singleton', '>= 0.0.5'