name         'gsick-jetty'
version      '0.0.9'
source       'https://github.com/gsick/puppet-jetty.git'
author       'Gamaliel Sick'
license      'MIT'
summary      'Jetty installation and configuration module'
description  'Puppet module for installing and configuring Jetty'
project_page 'https://github.com/gsick/puppet-jetty'

dependency   'puppetlabs/stdlib', '>= 4.5.0'
dependency   'puppetlabs/java',   '>= 1.2.0'